### ISSUE TITLE
@neutrinojs/jest does not support some coverage options from .neutrinorc.js

### ISSUE THREAD

**Issue by flouc001** [neutrinojs/neutrino#1015]
### Bug

Please try to answer the following questions:

- What version of Neutrino are you using?
8.3.0

- Are you trying to use any presets? If so, which ones, and what versions?
Yes:
@neutrinojs/airbnb 8.3.0
@neutrinojs/jest 8.3.0
@neutrinojs/react-components 8.3.0

- Are you using the Yarn client or the npm client? What version?
Yarn v1.9.4

- What version of Node.js are you using?
Node v8.9.3

- What operating system are you using?
MacOS 10.13.4

- What did you do?
Added coverage options to the jest preset via `.neutrinorc.js` like so:
```js
['@neutrinojs/jest', {
  collectCoverage: true,
  collectCoverageFrom: '**/src/components/**/*.{js,jsx}'
}]
```

- What did you expect to happen?
Coverage reports to be generated.
- What actually happened, contrary to your expectations?
No coverage was run.

**Comment by edmorley** [comment]
Hi!

To generate coverage reports when using the Neutrino 8 Jest preset, the `--coverage` option needs to be passed on the command line. See:
https://neutrinojs.org/packages/jest/#coverage-reporting

There should be no changes required to the Jest configuration in `.neutrinorc.js`.

Could you try that and report back with how it went? :-)

**Comment by edmorley** [comment]
Looking at the Jest docs, using `collectCoverage: true` seems to be equivalent to `--coverage` on the CLI, however I'm presuming the reason that didn't work with Neutrino 8, is since it calls the API with an explicit `coverage: args.coverage` which will be `false` unless `--coverage` was passed to `neutrino test`, and that presumably takes precedence:
https://github.com/neutrinojs/neutrino/blob/v8.3.0/packages/jest/src/index.js#L118
https://jestjs.io/docs/en/configuration.html#collectcoverage-boolean

With Neutrino 9 (on `master`, not yet released), Jest's own CLI is used instead of invoking Jest by its API, and so I believe `collectCoverage: true` will then work as expected, should you wish to avoid needing to pass `--coverage` on the command line.

**Comment by flouc001** [comment]
Hi @edmorley, maybe using `collectCoverage` was a poor example. Neutrino's docs state that you can use the jest property in the configuration file to supply any options jest recognises and it will apply them.

Take the snippet I provided above for example. I have set two options that I would like to be passed on to jest ( `collectCoverage` and `collectCoverageFrom` ). Currently it seems these settings get lost somewhere in the code for the neutrino preset.

If I run the `neutrino test --coverage` it still completely ignores the `collectCoverageFrom` option, this is not expected behaviour.

**Comment by edmorley** [comment]
The options passed to the preset are merged using deepmerge, here:
https://github.com/neutrinojs/neutrino/blob/f741f9e33542f69895871f9c0956bf5e15bd1785/packages/jest/src/index.js#L56-L76

This does mean that for array based values, the arrays will be merged, rather than be replaced. As such at present, you'll end up with both the old and new value in the `collectCoverageFrom` array. 

The Neutrino 8 Jest preset writes the configuration to a temporary file (a bit hacky and has been rewritten for Neutrino 9 on `master`) - if you find that file in the temporary directory, you can confirm what values are actually being written out.

Also, the default value for `collectCoverageFrom` should already include the `'**/src/components/**/*.{js,jsx}'` path, so long as it's under the `neutrino.options.source` directory? Was that not working?

**Comment by flouc001** [comment]
I guess the merge is the undesirable operation in my case. Is this something that will be overridable in future versions?

**Comment by eliperelman** [comment]
In v9 you'll be able to overwrite the value from the `jest.config.js` file:

```js
const neutrino = require('neutrino');

module.exports = neutrino().jest(config => {
  config.collectCoverageFrom = /* whatever you overwrite */;

  return config.
});
```

**Comment by flouc001** [comment]
That sounds great, I guess the best option is to wait for v9.

**Comment by eliperelman** [comment]
Closing as resolved.

**Comment by edmorley** [comment]
@flouc001, Hi! We've just released a Neutrino 9 beta, if you'd like to try it out? See #1129.
