### ISSUE TITLE
Consider removing TypeScript extensions when no preset supports them

### ISSUE THREAD

**Issue by eliperelman** [neutrinojs/neutrino#1091]

**Comment by edmorley** [comment]
I think we should just remove them by default, since it gives the misleading impression that TypeScript is supported out of the box, and from what was said in #1044, their inclusion actually makes certain workflows more complicated.

Any third-party TypeScript preset could always then check `neutrino.options.extensions` and issue a warning if the user hasn't added added them in.

Long term it would be great if the middleware API allowed presets to declare which extensions they supported, and aggregated the list of extensions prior to the rest of the preset functionality being executed. (Since at the moment presets are only able to adjust extensions at the time they run, which is too late to adjust rules already configured eg `lint`)
