### ISSUE TITLE
Neutrino v9 Status? 

### ISSUE THREAD

**Issue by eltonjuan** [neutrinojs/neutrino#1095]
Just curious what the status on releasing Neutrino v9 with Webpack 4 and Babel 7 support? Would really like to update some projects to take advantage of new features in both of those libraries, but don't want to give up neutrino just yet. 

Thanks!

**Comment by edmorley** [comment]
Hi! We're very keen to get Neutrino 9 released soon, since we have projects that would benefit massively from the various performance improvements. The remaining items in the milestone are:
https://github.com/neutrinojs/neutrino/milestone/6

However many of those can wait until the final release (apart from say the docs pieces, which I have almost complete locally) - so I'm hoping by this weekend we can at least have an alpha (or beta, depending on what we decide to call it) released :-)

**Comment by edmorley** [comment]
@eltonjuan Hi! We've just released a Neutrino 9 beta, if you'd like to try it out? See #1129.

**Comment by eltonjuan** [comment]
@edmorley congrats! and thanks for all your hard work 👍 will check it out now
