### ISSUE TITLE
Cannot override main entry template without also specifying the path to the entry again

### ISSUE THREAD

**Issue by eliperelman** [neutrinojs/neutrino#1178]
With the Neutrino 9 beta, if you try overriding the template, you will get an exception:

```js
module.exports = {
  options: {
    root: __dirname,
    mains: {
      index: {
        template: join(__dirname, "src/template.ejs"),
      },
    },
  },
  // ...
};
```

```
❯ yarn build
yarn run v1.10.1
$ webpack --mode production
/Users/eli/code/project/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

If you re-specify the entry, it works as expected:

```js
module.exports = {
  options: {
    root: __dirname,
    mains: {
      index: {
        entry: join(__dirname, "src/index.js"),
        template: join(__dirname, "src/template.ejs"),
      },
    },
  },
  // ...
};
```

**Comment by edmorley** [comment]
For a single entry-point project I would expect the html options to be set via `html` in the web preset options instead (since the mains options are meant as overrides). However I can see this still being an issue when eg multi-entrypoint and the first page wants a custom template but the others are using the global default via the `html` preset option.

**Comment by eliperelman** [comment]
My thought was the solution should be a merge of the existing value if its an object.

**Comment by edmorley** [comment]
Would you mind taking this one?
