### ISSUE TITLE
node preset: Warn not to use yarn/npm start in production

### ISSUE THREAD

**Issue by helfi92** [neutrinojs/neutrino#1188]
Given that the bundle size in node applications is less of a concern than in web apps, we can be tempted to run `yarn start` in production. For node applications, we should mention not to run in `yarn start` in production since it will enable development settings and that could possibly be a security vulnerability or really just slower performance.

**Comment by eliperelman** [comment]
The `yarn start` script, while is recommended for a development command, is not actually under Neutrino's control, since it is defined by the user in their project. We have a recommendation when building the project in the README:

https://github.com/neutrinojs/neutrino/tree/master/packages/node#building

Does this need to be revised?

**Comment by edmorley** [comment]
The context was:
https://mozilla.logbot.info/frontend-infra/20181022#c15502381-c15502515

**Comment by constgen** [comment]
My recommendation would be to always start an app in production with 

```node .```

That's why you need to set a correct path to main file in the package.json:

```json
{
  "main": "build/index.js"
}
```
So this should not conflict with npm commands
