### ISSUE TITLE
Setting options.source breaks linting

### ISSUE THREAD

**Issue by sphet** [neutrinojs/neutrino#1192]
I am using the react,jest and standardjs preset on 8.3.0. I have set my source folder to something other that src, and outside of the immediate directory (../../project/src/...).

Building without the linter works fine, but with it on I get a host of errors: 

Unable to resolve path to module 'react-dom' (import/no-unresolved) at ..\..\sourcefiles\src\index.jsx
Missing file extension for 'react-dom' (import/extensions) at ..\..\sourcefiles\src\index.jsx

So clearly the linter isn't getting my source or somehow my modules path.

I have tried setting options.node_modules but that doesn't help.

Any insight please. Running Windows7 and yarn

**Comment by edmorley** [comment]
Hi!

Those ESLint errors are generated by [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import), which uses `package.json` to determine:
* if any of the imports found in the source are missing from `dependencies` ([import/no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md))
* which imports should have a file extension vs not ([import/extensions](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md))

It sounds like the plugin is not finding the correct `package.json`, and so doesn't know that `react-dom` is correctly in `dependencies`. This also causes the follow-on `import/extensions` error, since it doesn't then know to give `react-dom` a "free pass" to omit the extension.

I'm presuming this could be fixed by adjusting the resolver settings here:
https://github.com/benmosher/eslint-plugin-import#resolvers

Or alternatively adjusting the rule settings via any of:
https://github.com/benmosher/eslint-plugin-import/blob/master/README.md#importignore
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md#ignore

The plugin readme mentions having both node and webpack resolvers, but it's not clear whether they are both enabled by default, or just the node resolver. If using the webpack resolver might help this use-case, then I would suggest trying the Neutrino 9 beta, which actually has a `webpack.config.js` file that it seems may be used by the webpack resolver for hints as to settings:
https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/README.md

**Comment by edmorley** [comment]
Closing as answered - but happy to reopen if I missed anything :-)
