### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by viperfx** [neutrinojs/neutrino#1196]
This is the message I get when trying to build a js file, thats an entry point to a react app.

```
$ neutrino build
✖ Building project failed
./user-settings/index.js
Module parse failed: Unexpected token (15:4)
You may need an appropriate loader to handle this file type.
|
| const load = () => render((
|     <Provider store={store}>
|         <App />
|     </Provider>
 @ multi ./user-settings/index.js
error Command failed with exit code 1.

```

**Comment by edmorley** [comment]
Hi!

You've deleted the issue template that asked for additional information.
Please could you add that information?

**Comment by constgen** [comment]
Probably this is because you wrote JSX in JS file. Rename the extension: `index.jsx`

**Comment by edmorley** [comment]
> Probably this is because you wrote JSX in JS file. Rename the extension: `index.jsx`

When using `@neutrinojs/react`, JSX can be written in both `.jsx` and `.js` files (it's only ESLint rules from the AirBnb preset that would display a preference), so that won't be the reason.

More likely is that either:
(a) the wrong Neutrino preset is being used eg web instead of react
(b) there is a typo in their `index.js` that we can't see from the excerpt above

Either way we need more information first :-)

**Comment by edmorley** [comment]
Closing since the issue was incomplete. Happy to reopen if more information is provided :-)
