### ISSUE TITLE
Docs - missing CLI installation step 

### ISSUE THREAD

**Issue by cweekly** [neutrinojs/neutrino#1211]
The docs mention `yarn create @neutrinojs/project ...` and later make reference to using the `neutrino` CLI, but nowhere is the basic step mentioned `yarn global add neutrino`.

Invoking neutrino in package.json npm scripts works bc it's found locally in `./node_modules/...` but I think its omission from the docs was an oversight.

MacOS 10.13.6 (High Sierra)
Node v10.13.0
Yarn v1.12.3
Neutrino v8.3.0

**Comment by edmorley** [comment]
Hi! Thank you for opening an issue - resolving anything that's unclear/incorrect in the docs is a high priority :-)

The `neutrino` must never be installed globally, only the `@neutrinojs/create-project` package (and if using the "create" feature of eg newer yarn, it handles that install automatically).

Instead, the `neutrino` command must be used from local `node_modules`, similar to the way eslint or webpack are used. To save having to reference them by full `./node_modules/...` path, it's common to run them via yarn/npm instead, since they automatically add `./node_modules/.bin/` to `PATH`.

There are two ways to run a command via yarn/npm:
1. By adding it to the `scripts` section in `package.json` ([docs](https://docs.npmjs.com/misc/scripts)) - for example:
```js
{
  // ...
  "scripts": {
    "build": "neutrino build"
  }
}
```
2. By passing arbitrary command names to yarn/npm (even if they are not in `scripts`) - for example
```bash
yarn run neutrino --help
npm run neutrino --help
# The `run` can be omitted if desired
yarn neutrino --help
npm neutrino --help
```

As such any time the docs say to run `neutrino <command>` they really mean to run `yarn neutrino <command>` or `npm neutrino <command>`.

It appears that the individual package pages do list the full commands - eg:
https://neutrinojs.org/packages/web/#yarn

However the CLI and usage pages don't:
https://neutrinojs.org/cli/
https://neutrinojs.org/usage.html

For Neutrino 9 we've actually moved away from the Neutrino CLI and reworked a bunch of the docs, so the CLI page no longer exists, but the usage page could still do with some tweaks:
https://master.neutrinojs.org/usage/

(If you'd like to try out the Neutrino 9 beta, see #1129)

**Comment by cweekly** [comment]
Thanks @edmorley, I appreciate your detailed reply.
Tangent: With reluctance, I think I need to table using Neutrino for now. Don't want to invest in Neutrino 8, given how radically everything's about to change in 9. I like the new direction, but timing is everything. Good luck w/ 9, and hopefully I'll "see" you in 2019.
Slainte,
Chris

**Comment by edmorley** [comment]
We're using the Neutrino 9 beta in several production Mozilla sites, if that helps at all. The final release is mostly waiting on me finishing off the last few "technically breaking but won't affect most people" changes.

**Comment by cweekly** [comment]
Thanks Ed,
Good to know.
