### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by dantman** [neutrinojs/neutrino#1269]
There is no TypeScript or CofeeScript preset for Neutrino v9.

The `neutrino-preset-typescript` has not been updated in 2 years so it can't really count as a preset and it uses `awesome-typescript-loader` which doesn't appear to fully support webpack 4 or the latest version of TypeScript.

**Comment by dantman** [comment]
I've tried adding local customization to handle coffescript with coffeescript-loader.

However neutrino seems to have a general problem that makes it difficult/impossible to create middleware to add coffeescript 2 or typescript (when transpiled with babel or only using ts-loader to transpile to es2015+).

These types of configurations need babel-loader to follow the coffee/ts loader (or extend the babel-loader in a separate rule). And in the context of neutrino this babel-loader needs a copy of the same babel-loader config present in the js/compile rule that `@neutrino/web` defines.

**Comment by kalekseev** [comment]
With `@babel/typescript` it's quite simple to setup:

```
        babel: {
          presets: ['@babel/typescript'],
        },
    ...
    neutrino => {
      // tsc and tslint checks
      neutrino.config.plugin('fork-ts-checker').use(ForkTsCheckerWebpackPlugin, [
        {
          checkSyntacticErrors: true,
          tslint: true,
        },
      ]);
      neutrino.config.resolve.extensions.add('.tsx');
      neutrino.config.resolve.extensions.add('.ts');
      neutrino.config.module.rule('compile').test(/\.(wasm|mjs|jsx|js|tsx|ts)$/);
```

Not sure is it worth to create a preset just for that.

**Comment by dantman** [comment]
Ok, the babel version isn't too hard. Though I presume there are are a fair number of people that actually want to use ts-loader. And there is no Babel version for CoffeeScript, so we still have the issue of these modes missing the babel config.

**Comment by slikts** [comment]
CoffeeScript largely lacks relevance these days, so it's probably not useful to invest resources in.

**Comment by chaiyilin** [comment]
> With `@babel/typescript` it's quite simple to setup:
> 
> ```
>         babel: {
>           presets: ['@babel/typescript'],
>         },
>     ...
>     neutrino => {
>       // tsc and tslint checks
>       neutrino.config.plugin('fork-ts-checker').use(ForkTsCheckerWebpackPlugin, [
>         {
>           checkSyntacticErrors: true,
>           tslint: true,
>         },
>       ]);
>       neutrino.config.resolve.extensions.add('.tsx');
>       neutrino.config.resolve.extensions.add('.ts');
>       neutrino.config.module.rule('compile').test(/\.(wasm|mjs|jsx|js|tsx|ts)$/);
> ```
> Not sure is it worth to create a preset just for that.

the thing is should we stick with babel or tsc?
as [TypeScript and Babel 7](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/)  point out, there are subtle differences between these two

**Comment by stevehawley** [comment]
Running babel for transpilation seems to be the minimum needed, but as a typescript user I do want the build to fail if there are type checking problems. That can be accomplished by modifying the build script in the package.json, but I think including it all in the preset encourages consistency across projects which is part of why I want to use neutrino.

**Comment by kalekseev** [comment]
> the thing is should we stick with babel or tsc?
as [TypeScript and Babel 7](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/) point out, there are subtle differences between these two

babel-typescript is more flexible, with it you can do everything that requires babel compilation without convoluted pipelines

> Running babel for transpilation seems to be the minimum needed, but as a typescript user I do want the build to fail if there are type checking problems.

`ForkTsCheckerWebpackPlugin` fails build with non zero exit code

**Comment by prasannavl** [comment]
I don't think it's a great idea to depend only on babel-typescript. I've had weird bugs using it, and many out of the box libraries in the wild not working well with it. 

For instance, subclassing `Dexie`, with babel-typescript ends up with weird bugs out of the box. I think the best way is to somehow expose the babel module config, so that it can be referenced and preceded by the typescript or other such pre-transformers.

**Comment by prasannavl** [comment]
Currently, I use whipped this up, and seem to work rather well: 

```js
function createTypeScriptPreset(options = {}) {
  return ({ config }) => {

    if (options.fork !== false) {
      config.plugin('fork-ts-checker').
        use(require("fork-ts-checker-webpack-plugin"), [
          {
            checkSyntacticErrors: true,
            tslint: false,
            ...options.forkChecker
          },
        ]);
    }

    let ext = config.resolve.extensions;
    ext.prepend('.ts');
    ext.prepend('.tsx');

    let babelOpts = config.module
      .rule("compile")
      .use("babel")
      .get("options");

    config.module.rule("ts")
      .test(/\.tsx?$/)
      .use("babel")
      .loader(require.resolve("babel-loader"))
      .options({ ...babelOpts, ...options.babel })
      .end()
      .use("tsc")
      .loader(require.resolve("ts-loader"))
      .options({ transpileOnly: options.fork !== false, ...options.ts })
      .end();
  };
}
```

**Comment by eliperelman** [comment]
I used a middleware pattern like the following to optionally enable either TypeScript or Flow support in a build preset:

https://github.com/ConduitVC/neutrino-presets/blob/master/packages/node/index.js

I feel like an external preset for each could work, but it may be possible to just bake this into compile-loader and dependent presets.

```js
neutrino.use('@neutrinojs/compile-loader', {
  flow: true, // or:
  typescript: true
});
```

Thoughts?

**Comment by edmorley** [comment]
One issue with baking support into the compile preset is that it then means everyone gets the typescript dependencies - I'm presuming they are not very lightweight, once type checker support etc (and not just Babel handling) factored in.

**Comment by srgreen00** [comment]
Hi, has anyone been able to get Jest tests running with Typescript and Neutrino combination?  If so, how was it approached?
Weʻve been able to run and build with the suggestions above, but no luck on the tests.

**Comment by kalekseev** [comment]
@srgreen00 one variant is to use ts-jest

jest preset in .neutrionrc.js (ts related part only):

```
    [
      '@neutrinojs/jest',
      {
        transform: {
          '^.+\\.tsx?$': 'ts-jest',
        },
        moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
        ...
      },
    ],
```

jest.config.js:

```
const neutrino = require('neutrino');

module.exports = neutrino().jest();
```

**Comment by slikts** [comment]
Unfortunately not supporting TypeScript rules Neutrino out for serious library development.

**Comment by slikts** [comment]
Sorry, my comment was not intended to be inflammatory, but providing TypeScript type definitions is a significant convenience for library consumers, as it integrates with the code intelligence features in common editors, and it also provides a baseline for API documentation, as well as enabling auto-generated standalone API documentation. Particularly since Flow has been losing relevance, TypeScript is more and more recognized as the go-to specifically for library development, and the lack of support is a notable omission in `@neutrinojs/library`. The other alternative is JSDoc, which has significant downsides.

**Comment by seaneking** [comment]
Has there been any further work on adding a Typescript preset to Neutrino? I think it's easily popular enough now to warrant reopening this discussion. As far as implementation, I think adding it as middleware which just configures the Babel for Typescript is the lowest hanging fruit and the most flexible setup. If you need to use `tsc` itself, you can setup something custom (perhaps document this in the middleware docs)

**Comment by laurib** [comment]
Typescript support is so much needed

**Comment by imben1109** [comment]
React + Typescript Support is needed

**Comment by SFM61319** [comment]
Typescript support is very needed (maybe as a parameter like in `create-react-app`? i.e., `npx @neutrinojs/create-project project-name --template typescript`). It's been over two years since the issue has been opened, and many are requesting for the same. Please consider this request. Especially since many are making react apps in typescript these days, and the lack of react typescript components in neutrinojs will only push them away towards other component libraries compatible with typescript.  
  
Thank you.

**Comment by davidje13** [comment]
Since people keep bumping this thread:

The packages I created are now quite stable and widely used (weekly downloads are over 10% of Neutrino's own downloads).

You can find them on NPM:

- [neutrinojs-typescript](https://www.npmjs.com/package/neutrinojs-typescript)
- [neutrinojs-typescript-eslint](https://www.npmjs.com/package/neutrinojs-typescript-eslint)

There is no integration with neutrino's bootstrapping tool, but it is easy enough to use the bootstrapping tool to build a project without TypeScript, then add TypeScript support by following the READMEs. Alternatively you can see some example projects: https://github.com/davidje13/neutrino-typescript-example and https://github.com/davidje13/neutrino-typescript-react-example

I encourage you to use these packages, report any bugs, and eventually they may get merged in to core neutrino. The main blocker to this at the moment is just that they don't quite follow Neutrino's philosophy for configuration, due to TypeScript not natively supporting js-based configuration (see the issue tracker of the project for a discussion on this).
