### ISSUE TITLE
@neutrinojs/react Add URL conversion plugin 

### ISSUE THREAD

**Issue by xyyjk** [neutrinojs/neutrino#1282]
By default, [html-loader](https://github.com/neutrinojs/neutrino/blob/master/packages/html-loader/index.js#L11) will convert `<img src="image.png">` to `require('./image.png')`.

There is no such function in React/JSX. 

[babel-plugin-transform-jsx-url](https://www.npmjs.com/package/babel-plugin-transform-jsx-url) can solve this problem in React.

### before
```
import logo from './logo.png';
<img src={logo} />
```

### after
```
<img src="./logo.png" />
```

**Comment by edmorley** [comment]
Hi!

This should already work with no changes required, since when webpack parses the JSX file, it will see the `.png` import and process it using `url-loader`, thanks to:
https://github.com/neutrinojs/neutrino/blob/01319690e176dc66310e888054a84a0743cfb772/packages/image-loader/index.js#L15-L21

`url-loader` then either:
* (if the file is above the size threshold) converts the file to a filepath (`./logo.png`) and internally tells webpack to copy the file to the output/build directory
* (if the file is under the size threshold) inlines the file as a `data:` URI
(see https://github.com/webpack-contrib/url-loader#url-loader)

Are you seeing something different? If so, that seems more like a bug, and not something that should require the use of another Babel plugin - and it would be great to have a reduced testcase repository to try out.

**Comment by xyyjk** [comment]
Hi ~ 

This is a demo:
https://github.com/xyyjk/neutrino_react/

There are two img tags in the component.
https://github.com/xyyjk/neutrino_react/blob/193bdefa7b4e6309322b53b2a6bf4a6a24d1387c/src/index.js#L6-L12

```jsx
const App = () => (
  <> 
    <h1>Hello world!</h1>
    <img width="100" src={logo} />
    <img width="100" src="./logo.png" />
  </>
);
```


The default is this:

<img width="720" alt="20190207-233135" src="https://user-images.githubusercontent.com/2508421/52422659-76522e80-2b31-11e9-8bd7-cd9f27184fd6.png">


This is because `url-loader` can only parse the way that require/import introduces resources.

When the babel plugin is used, the full image path can be automatically imported.
https://github.com/xyyjk/neutrino_react/blob/master/.neutrinorc.js#L1-L9

```js
module.exports = {
  use: [
    ['@neutrinojs/react', {
       babel: {
         plugins: ['transform-jsx-url']
       }
    }]
  ]
};
```

<img width="699" alt="20190207-233253" src="https://user-images.githubusercontent.com/2508421/52423062-4b1c0f00-2b32-11e9-925d-2b0c2609708d.png">

**Comment by eliperelman** [comment]
Since this can be controlled in userland, and is pretty specific to JSX, I'm going to close this one out. We will re-open if we reconsider this feature in the future. Thank you!

**Comment by edmorley** [comment]
Also in general I think using `require()` is preferred over having tooling to "fix up" hardcoded file references. The exception being template formats which don't support using JS (such as HTML, hence `html-loader` supports doing this) - but that doesn't apply to JSX.
