### ISSUE TITLE
Error: React-Hot-Loader: AppContainer should be patched

### ISSUE THREAD

**Issue by sylvainbaronnet** [neutrinojs/neutrino#1291]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using?
8.3.0
- Are you trying to use any presets? If so, which ones, and what versions?
React
- Are you using the Yarn client or the npm client? What version?
Yarn v1.13.0
- What version of Node.js are you using?
v11.8.0
- What operating system are you using?
mac
- What did you do?
only `yarn create @neutrinojs/project somename` and `yarn start`
- What actually happened, contrary to your expectations?
following error : 

<img width="638" alt="screenshot 2019-02-01 at 16 15 14" src="https://user-images.githubusercontent.com/1569516/52128887-ce26fc00-263e-11e9-8333-1bf8f4715cab.png">

**Comment by edmorley** [comment]
Hi! I believe this is because v8 of the Neutrino create-project tool doesn't pin `react-hot-loader` to a specific version, and so breaking changes made in `react-hot-loader` v4 get pulled in, even though Neutrino v8 doesn't support that version.

I would either:
* continue to use Neutrino 8 and update `package.json` to use `react-hot-loader` v3 instead, then re-run `yarn`
* try out the Neutrino 9 beta, which both correctly pins dependencies like `react-hot-loader` to the supported version, plus now supports `react-hot-loader` v4 anyway. For instructions on how to try our the beta, see #1129 

Hope that helps! :-)

**Comment by sylvainbaronnet** [comment]
thanks! will try v9 then

**Comment by eliperelman** [comment]
Closing as fixed in Neutrino 9.

**Comment by Jossnaz** [comment]
@eliperelman so you let all users who start with your project to run into this? _all_ of them have to google the issue, land here, and then figure out how to install neutrino 9? this makes me expect a lot more issues just like this with this project. The "stable" release doesnt work, yikes... not sure what to expect next. Nothing good that is sure.
