### ISSUE TITLE
Remove options.tests entirely

### ISSUE THREAD

**Issue by eliperelman** [neutrinojs/neutrino#1331]
### Bug or issue?

We have several issues around overriding test locations. In an earlier era, it was common to have all tests located in a single directory, but the landscape has shifted to additionally supporting tests anywhere.

https://github.com/neutrinojs/neutrino/issues/1205
https://github.com/neutrinojs/neutrino/issues/1209

Should we just remove the `tests` option entirely now?

cc: @neutrinojs/core-contributors

**Comment by edmorley** [comment]
What would replace it? :-)

**Comment by yordis** [comment]
@edmorley point to `src` (source) by default.

For the most part (because Angular folks still like multiple folders), people are used to having the test files in the `src` folder.

But this is just my bias opinion.

Since this value depends on the test framework that you are using, I would simply remove it.

Let the presets related to a specific framework to decide the default path.

**Comment by edmorley** [comment]
I think there are a few overlapping questions/bugs here:
1. what test locations should Neutrino and/or its presets default to?
2. should users be able to override these default locations?
3. if so, how?
4. if so, should setting the source directory to be the same as the `src` directory be supported? (ie: #1209)

Personally I think (2) and (4) are an easy "yes" - I just don't know what is best for (1) and (3).

If we want to do something other than just fixing #1209 (which I see as a bug), then it's likely a breaking change, so we'd need to make it soon, or it won't make Neutrino 9.

Any more thoughts on this topic would be helpful, since I'm short of inspiration :-)
