### ISSUE TITLE
[v9] options.extensions not used

### ISSUE THREAD

**Issue by rkostrzewski** [neutrinojs/neutrino#1404]
### Bug

Please try to answer the following questions:

- What version of Neutrino are you using?
9.0.0-rc.3
- Are you trying to use any presets? If so, which ones, and what versions?
@neutrinojs/react@9.0.0-rc.3 (should be visible with compile-loader only)
- Are you using the Yarn client or the npm client? What version?
npm@6.7.0
- What version of Node.js are you using?
node@10.8.0
- What operating system are you using?
macOS
- What did you do?
1. Run `npx @neutrinojs/create-project@9.0.0-rc.3` with only `React` on
2. Edited `.neutrinorc.js` to look like this:
```
const react = require('@neutrinojs/react')

module.exports = {
  options: {
    root: __dirname,
    extensions: ['mjs', 'jsx', 'js', 'ts'], // <- added 'ts' extension
  },
  use: [
    react(),
  ],
}
```
3. Created empty `src/index.ts` file and removed `src/index.js`/
4. Run `webpack --mode production`
- What did you expect to happen?
Build finishes successfully because `src/index.ts` is resolved by webpack and processed by babel
- What actually happened, contrary to your expectations?
Build fails with error:
```
ERROR in multi ./src/index
Module not found: Error: Can't resolve '/Users/rkostrzewski/GitHub/coinsy/web/src/index' in '/Users/rkostrzewski/GitHub/coinsy/web'
 @ multi ./src/index index[0]
```

Based on quick investigation this might occur because `options.extensions` is not used in `Neutrino.getOptions` instead `moduleExtensions` variable is used that is initialised only with `source` from `neutrino/extensions` module (changing that declaration to include `options.extensions` yields a successful build however on v8 the code looks the same yet extension `'foo'` works in v8)

**Comment by edmorley** [comment]
Hi! Thank you for reporting. Yeah this looks like a bug.

@eliperelman it seems like we should be setting the default extensions list here (rather than declaring `moduleExtensions` the line before):
https://github.com/neutrinojs/neutrino/blob/46793f28a886fe83dc52d7af849e1311fe444966/packages/neutrino/Neutrino.js#L31-L34

...and then referring to `options.extensions` (instead of `moduleExtensions`) here:
https://github.com/neutrinojs/neutrino/blob/46793f28a886fe83dc52d7af849e1311fe444966/packages/neutrino/Neutrino.js#L83-L91

We should also add some tests for this, since there currently aren't any for `extensions` here:
https://github.com/neutrinojs/neutrino/blob/master/packages/neutrino/test/api_test.js

Thoughts?

**Comment by eliperelman** [comment]
@edmorley it's funny you mention that, because I started doing exactly that yesterday. Then I remembered that the order of these extensions is very important, so I'm wondering if setting this in options should overwrite instead of merge?

**Comment by edmorley** [comment]
Ah yes I think it should override.

**Comment by edmorley** [comment]
@eliperelman hi :-) Did you have a WIP for this locally?

**Comment by timkelty** [comment]
@eliperelman, @edmorley If no one has a WIP of this, I can take a stab this week!

**Comment by timkelty** [comment]
Thanks for the clear bug report, @rkostrzewski. Just pushed a PR: #1477
