### ISSUE TITLE
Make it easier to use `useBuiltIns: 'usage'`

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#1470]
AFAIK, if you want to change `@babel/preset-env`'s `useBuiltIns` option, you have to pass the preset config in its entirety, e.g.: 

```
const web = require('@neutrinojs/web');
module.exports = {
  use: [
    (neutrino) => neutrino.use(
      web({
        babel: {
          presets: [
            [
              require.resolve('@babel/preset-env'),
              {
                useBuiltIns: 'usage',
                debug: neutrino.options.debug,
                corejs: 3,
              },
            ],
          ],
        },
      })
    )
  ]
}
```

…would it be worth it to make this easier to change via options (similar to how we have `options.targets`)?

**Comment by edmorley** [comment]
Perhaps we should switch from `entry` to `usage` by default? iirc the reason I didn't use `usage` in the past (which upgrading to Babel 7) was that (a) it was more buggy then, (b) it was harder for people to opt out if they didn't need to use a polyfill at all.

However since then, I'm presuming the bugs have been worked out solving (a), and we now dynamically set it to `false` based on whether `core-js` is found, which resolves (b).

Either way we should probably also now replace the `@babel/polyfill` references in the docs with `core-js`.

The description of entry vs usage can be seen [here](https://babeljs.io/docs/en/babel-preset-env#usebuiltins).

**Comment by timkelty** [comment]
> Perhaps we should switch from entry to usage by default

Sounds like that could be a good move. Yeah – it used to be noted as "experimental" in Babel docs, but doesn't seem to be any longer.

I just started using it has seemed to work great so far, and dropped my bundle size alot.

> Either way we should probably also now replace the @babel/polyfill references in the docs with core-js.

Yep!

**Comment by timkelty** [comment]
@edmorley I can squeeze in a PR tomorrow if you think changing this to `usage` would be good for v9. /cc @neutrinojs/core-contributors

**Comment by edmorley** [comment]
@timkelty yeah let's do it :-)

**Comment by timkelty** [comment]
K, I'll PR today!
