### ISSUE TITLE
is it possible to load an existing webpack.config.js?

### ISSUE THREAD

**Issue by chaiyilin** [neutrinojs/neutrino#1516]
i am just wondering is it possible/logical to support loading an existing webpack.config.js into neutrino and start from here?
reason being is many projects already have webpack.config.js in place and people are already comfortable with it. on the other hand we can think of neutrino can provide some enhancing to the existing webpack.config.js. therefore this hybrid approach.

**Comment by chaiyilin** [comment]
seems answer is here:
[](https://neutrinojs.org/faq/#can-i-just-re-use-my-existing-webpack-configuration)
but not quite convincing.

**Comment by edmorley** [comment]
@chaiyilin Hi! Sorry for the delayed reply.

From a practical point of view, importing an existing Neutrino config would be hard, since the webpack config doesn't have the concept of named plugins/rules/... so Neutrino would have to auto-generate names. Then users would have to guess as to what those names were, when using Neutrino's APIs to apply customisation on top. And since there are many different ways that webpack configs can be written (several different styles etc), it would take a lot of effort to read that in and try and translate it to a Neutrino config.

In addition, I would argue that many people's webpack configs contain bad patterns, or at the least chose approaches that might conflict with Neutrino's preset's config, so taking a simplistic merging approach would often give a bad result.

As such whilst I can see that it would be useful if there was a way to rapidly speed up learning Neutrino config or translating an existing config, I don't think there's a huge amount we can do here (and not without it requiring lots of engineering effort or having many edge cases/bugs).

One thing that might help for users in this position, would be to try picking a Neutrino preset, running `neutrino --inspect` (more details [here](https://neutrinojs.org/usage/#inspecting-the-generated-webpack-config)), and then using that as a way to compare to the existing config and seeing if any further adjustments are required.

Sorry to not have a better answer! :-)
