### ISSUE TITLE
Is there any way to make another script run before the neutrino related code run?

### ISSUE THREAD

**Issue by YahngSungho** [neutrinojs/neutrino#1565]
For the context, I want the app to disable React devtool. This is because React devtool makes the app very slow. In order to do that, I need to make certain script* run before `React` is loaded. But I don't know how to. Because neutrino's `index.jsx` imports `React` right from the beginning, and it is the first file to run. Sorry if I'm missing something.

*:
```
<script>
    // before React is loaded
    if (typeof window.__REACT_DEVTOOLS_GLOBAL_HOOK__ === 'object') {
        __REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function() {};
    }
</script>
```

**Comment by edmorley** [comment]
@YahngSungho Hi! 

> This is because React devtool makes the app very slow.

If you haven't already I'd report this performance issue as a bug against React devtool. 
I would also ask them if there is an easier way to disable React devtool than the `__REACT_DEVTOOLS_GLOBAL_HOOK__ ` method above.

> Because neutrino's index.jsx imports React right from the beginning

Neutrino doesn't inject an `index.jsx` or React (at least as of Neutrino 9+), do you mean the example template generated by `create-project` (https://github.com/neutrinojs/neutrino/blob/5fa090c7982bdaee2ea238e7c874e49a3958be99/packages/create-project/commands/init/templates/react/src/index.jsx#L1)? If so, you can customise that template to add an import the line before the React import, that includes the code above. You mean need to add an eslint-ignore so that ESLint doesn't complain about the import order.

For example something like:

```jsx
// index.jsx 
import './foo';
// ^^^ added line
import React from 'react';
import { render } from 'react-dom';
import App from './App';

render(<App />, document.getElementById('root'));
```

```js
// foo.js
// before React is loaded
if (typeof window.__REACT_DEVTOOLS_GLOBAL_HOOK__ === 'object') {
    __REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function() {};
}
```
