### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#1624]
Webpack 5 is is in RC, so presumably Neutrino v10 would include that.

Since the v9 release, development seems to have slowed a bit…I wanted to make a gut check with @neutrinojs/core-contributors and see who is still actively using Neutrino, and who might be available for continued development.

At the same time, it might be worthwhile to review the landscape and compare with other somewhat similar projects that have popped up, eg https://github.com/symfony/webpack-encore, and see where Neutrino fits.

/cc @neutrinojs/core-contributors @neutrinojs/admins

**Comment by edmorley** [comment]
@timkelty Hi! Hope you are well :-)

Thank you for opening this issue, both for having something open to track webpack 5 support (beyond the PR that's stalled), and also for checking in re project status.

Back when I was at Mozilla, I was an active user of Neutrino (as was Eli). However since then my work doesn't involve much front-end development, so I rarely use either Neutrino or webpack in general.

I agree there has been less activity since the Neutrino 9 release, though that is in part due to Neutrino having most features that I think it needs at this point - and as you say the next big milestone being webpack 5 support. 

About a year ago I did experiment with adding webpack 5 support, however there was still lots incompatible/missing/changing upstream so it wasn't worth more time investment at that point. The problem with Neutrino "supporting all the things" means that we pretty much have to wait until every single webpack plugin for every ecosystem is compatible, which means trying to add support early is hard. That said, I'm sure if I was using Neutrino day to day I would have tried to add support for React at least, if only to get the build performance wins early :-)

One of the biggest next steps for webpack 5 support is to make the relevant changes to webpack-chain. Since Vue CLI is using webpack-chain (and is highly popular) it's possible that they may be the best source of support for that.

> At the same time, it might be worthwhile to review the landscape and compare with other somewhat similar projects that have popped up, eg https://github.com/symfony/webpack-encore, and see where Neutrino fits.

Yeah I agree that there may be better options out there now.

Also in the end, a success condition for Neutrino would be for webpack to become as easily setup out of the box, so that all these layers of abstraction are no longer required. webpack is definitely closer to that than in the past - though still more work to do. If anything, perhaps investing open source hours into this would be a better use of time than working on Neutrino?

**Comment by Nic128** [comment]
https://github.com/neutrinojs/neutrino/pull/1674

I've been slowly testing different neutrino templates, found some bugs to which other people already have fixes for. I vote for an alpha v10 to be created if we can find someone to review the PR.

**Comment by myleftboot** [comment]
I'd be happy to help out with developing integration with Webpack 5.

**Comment by edmorley** [comment]
This depends on webpack-chain adding support for webpack 5 first - help wanted:
https://github.com/neutrinojs/webpack-chain/milestone/1

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
