### ISSUE TITLE
WebExtension preset

### ISSUE THREAD

**Issue by graingert** [neutrinojs/neutrino#306]
I know you're not actively looking for presets, but a preset supporting WebExtensions would directly further Mozilla's mission.

**Comment by constgen** [comment]
Pull request is welcome.
The most hard in implementation will be to setup the `neutrino start`. What should happen on this command?

**Comment by graingert** [comment]
@constgen launch a Firefox profile with the extension loaded

**Comment by graingert** [comment]
@constgen maybe even use a web socket to uninstall and reinstall the extension when it updates

**Comment by constgen** [comment]
I know that Firefox has a special API for livereloading extensions. But what about Chrome and Edge?

**Comment by graingert** [comment]
@constgen use HMR for those browsers?

**Comment by constgen** [comment]
Background process will not be reloaded in those browsers, will it?
You would like to have a reimplementation of https://github.com/mozilla/web-ext as a preset. Am I right.

**Comment by eliperelman** [comment]
I'm going to close this as something we aren't going to handle in core right now. If someone from the community wants to pick this up, that would be very appreciated!

**Comment by graingert** [comment]
Bummer

**Comment by eliperelman** [comment]
We are considering bringing this into core again. If you are interested in working on this, please let me know and I can point out a few resources for inspiration.

**Comment by helfi92** [comment]
@eliperelman I can look into that. Let me know how I can help :)

**Comment by eliperelman** [comment]
@helfi92 here's a few resources to help you get started:

- Look into the [web-ext tool](https://github.com/mozilla/web-ext). We may only need this tool for the run/start portion of it, since webpack should be able to handle the rest. Maybe we can use [webpack-webext-plugin](https://github.com/rpl/webpack-webext-plugin), maybe not.
- Check out some [webextension examples](https://github.com/mdn/webextensions-examples/tree/master/store-collected-images/webextension-with-webpack). Important things to note are creation of `background.js`, `popup.js`, and content scripts, as well as a manifest.json. Some of these we may be able to generate with create-project, and some we may be able to create at build time, I'm not sure.

**Comment by eliperelman** [comment]
Being worked on in #567.

**Comment by eliperelman** [comment]
Closing as we don't have anyone that could actively maintain this. Feel free to reopen if a patch is submitted with an active maintainer for this.

**Comment by crimx** [comment]
I've created a [neutrino-webextension](https://github.com/crimx/neutrino-webextension) preset which had been successfully used in couple of my own projects over the pass few months.

If you are looking for solutions please take a look and leave comments. If people find it useful maybe I can add it to the community presets list.
