### ISSUE TITLE
Should @neutrinojs/karma empty the default webpack entry point?

### ISSUE THREAD

**Issue by jackysee** [neutrinojs/neutrino#634]
I have instructed `@neutrinojs/karma` to only load `*all_test.js` files 

```
use: ['@neutrinojs/karma', {
  files: ['test/all_test.js'],
  webpackMiddleware: { noInfo: false, logLevel: trace }
}]
```

by using the log config above I can see that the `index` entry is also being compiled, which will be quite time consuming when the index entry grow large.

Currently, I just empty the entry point during test. So karma-webpack only compile necessary bundles:
```
    neutrino.config.when(process.env.NODE_ENV === 'test', () => {
        neutrino.config.entryPoints.clear();
    });
```
Should it be the default config?

**Comment by eliperelman** [comment]
According to the README on webpack-karma:

```js
// karma watches the test entry points
// (you don't need to specify the entry option)
// webpack watches dependencies
```

So it would seem that Karma now does this automatically, or maybe only for the test entry-points?

Thoughts @mozilla-neutrino/core-contributors? I would say this isn't a breaking change, but rather a bug.

**Comment by edmorley** [comment]
Given what the webpack-karma docs say, and that testing locally I can confirm karma doesn't use the entrypoints, I believe we should skip building them. 

In fact, on `master` (upcoming Neutrino 9), we now omit the entrypoints (as of #852):
https://github.com/neutrinojs/neutrino/blob/985e17992ea40618089940ccaba832cce347ec1c/packages/karma/index.js#L59

(compare to Neutrino 8: https://github.com/neutrinojs/neutrino/blob/v8.3.0/packages/karma/index.js#L61)

So this will be fixed in Neutrino 9.
