### ISSUE TITLE
Unable to pass options to @neutrinojs/karma after #852

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#907]
The `@neutrinojs/karma` preset used to allow passing options to it (and also adjust merging behaviour using the `override` option), but now exports only `neutrino => { ... }`.

This caused the treeherder karma config to silently break, such that it no longer runs any tests.

We should either:
* re-add the ability to pass options to the preset (like most of the other presets)
* make sure that trying to pass options doesn't silently fail, and also add this to the list of things we mention in the migration guide.

**Comment by edmorley** [comment]
Treeherder is probably going to start rolling it's own karma config for Neutrino 9, since our config differs quite a bit from that in `@neutrinojs/karma`. (eg we use Firefox not Chrome, jasmine not mocha, don't use coverage, and for legacy reasons use the karma-webpack "bundle all files together" approach.)

As such, we probably won't be using the ability to pass options (and set `override: true`) - so I have less of an opinion as to whether we should restore this feature. 

However if we decide not to, we should probably make the change in behaviour clearer, by emitting a warning/error if options are passed. (The same also applies to `@neutrinojs/mocha` and `@neutrinojs/jest`.)

**Comment by edmorley** [comment]
@eliperelman - thoughts on this?

**Comment by eliperelman** [comment]
I discussed this with @edmorley over IRC, and we came to the realization that the only reason we needed the overwrite functionality was because the middleware was also responsible for spawning the karma process. Now that these aren't coupled, doing an overwrite doesn't needed to be supported since you could simply *not use the middleware* but still launch karma from your own `karma.config.js`.
