### ISSUE TITLE
Support configuring multiple instances of @neutrinojs/style-loader from @neutrinojs/web

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/neutrino#964]
`test` and `modulesTest` are top-level options, but they should also be able to be set-per rule, if you don't want all loaders for all tests.

Report:
https://spectrum.chat/thread/45508553-d99b-46ff-a2b8-15910326f0ae

**Comment by timkelty** [comment]
I  _think_ we'd just have to add 
Hmm…or should the prescribed way of doing this just be to use style-loader twice?

**Comment by mrwillis** [comment]
I think one application is best. That way it works well with other presets(react, vue, etc) with the style property. Otherwise its kind of awkward and perhaps confusing if they see another style preset applied.

**Comment by timkelty** [comment]
@edmorley This would be nice for v9 if we can sneak it in. I'll see if I can fit some work in.

**Comment by timkelty** [comment]
Came up again here: https://spectrum.chat/thread/5770e7d3-f2b1-4c04-b3c5-f16ccb9e3d82

**Comment by timkelty** [comment]
So I started down this path but realized it doesn't make a ton of sense, because of the structure of `module.rules`. In the end we'd _need_ multiple rules with their own `test` and corresponding loaders, so it would be same end result as using `@neutrinojs/style-loader` a second time (as shown [here](https://spectrum.chat/thread/45508553-d99b-46ff-a2b8-15910326f0ae?m=MTUyOTkyNDU1MTgyMg==).

@mrwillis's [comment](https://github.com/neutrinojs/neutrino/issues/964#issuecomment-401490737) is valid though, as other middleware wouldn't know about the `style-2` rule (or whatever). Not sure Neutrino has a solution for that?

Might be that it isn't that big of a deal…/cc @edmorley @eliperelman

**Comment by edmorley** [comment]
It seems like the use-case of wanting to customise the style rules is pretty common (compared to customisation of other parts of the configuration), and something that is not overly straightforwards at present.

Perhaps we could add some additional options to `@neutrinojs/web` under `style`, which if used, cause it to use `@neutrinojs/style` twice? There's probably more we could do with the docs as well, with additional "how to" sections.

What would help with this is gathering a list of common configurations, since as someone who doesn't use anything but the default style loaders, I'm having trouble visualising the desired end result.

**Comment by timkelty** [comment]
> with additional "how to" sections

Yep. Adding an FAQ/How To would be nice: https://github.com/neutrinojs/neutrino/issues/747

> which if used, cause it to use @neutrinojs/style twice

Sure…though I think having people do this manually (helping them with an FAQ) wouldn't be so bad either.

The issue remains that you'll end up with second rule with a webpack-chain ID of something that is NOT "style". So if some middleware later relies on that to do something, it will miss the second rule. Older example from a v7 MW: https://github.com/barraponto/neutrino-preset-vue/blob/master/src/index.js#L9

It may be that this is more of a caveat we can call out, than an actual "problem". Manipulating the core "style" rule used to be more common before you could just pass loaders to `@neutrinojs/style`. I'm not sure it is so much anymore.

**Comment by edmorley** [comment]
I think that a preset that needs to manipulate the `style` rule is likely to be a top-level preset, and as such is in a position to control how the multiple style rules are created, so that shouldn't be a problem. For the 0.01% case where it might be - there's the webpack-chain API.

> Perhaps we could add some additional options to `@neutrinojs/web` under `style`, which if used, cause it to use `@neutrinojs/style` twice?

Perhaps we can do this as simply as allowing `style` to also be an array, where each element gets passed to a new instance of `@neutrinojs/style`?

**Comment by timkelty** [comment]
@edmorley yeah allowing an array seems pretty dead-simple to me :).

**Comment by edmorley** [comment]
Removing from the v9 milestone since this can be implemented in a non-breaking way, and so can be added in a minor version after the v9.0.0 release.
